package com.servicehub.entity;

public enum ServiceType {
    PLUMBING, ELECTRICIAN, CARPENTER, CLEANING, PAINTER,
    AC_REPAIR, REFRIGERATOR_REPAIR, WASHING_MACHINE_REPAIR,
    CCTV_INSTALLATION, WATER_PURIFIER_SERVICE,
    BEAUTICIAN, MAKEUP_ARTIST, FITNESS_TRAINER, YOGA_TRAINER, MASSAGE_THERAPIST,
    MOBILE_REPAIR, LAPTOP_REPAIR, COMPUTER_TECHNICIAN, WEB_DEVELOPER, APP_DEVELOPER,
    HOME_TUTOR, MUSIC_TEACHER, DANCE_TEACHER,
    DRIVER, PACKERS_MOVERS, EVENT_PLANNER
}
