spring.application.name=servicehub-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/servicehub
spring.datasource.username=postgres
spring.datasource.password=root@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080
# ============ STRIPE ============
stripe.secret.key=${STRIPE_SECRET_KEY}

# ============ SPRING MAIL (Gmail SMTP) ============
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
